name: Cronjob
on:
  schedule:
    - cron: '1 * * * *'


jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: print the hello world 
      run: echo 'hello world'